var f;f||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},f),ba="./this.program",ca=(a,b)=>{throw b;},da="object"==typeof window,h="function"==typeof importScripts,m="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n="",ea,u,v;
if(m){var fs=require("fs"),fa=require("path");n=h?fa.dirname(n)+"/":__dirname+"/";ea=(a,b)=>{a=w(a)?new URL(a):fa.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=ea(a,!0);a.buffer||(a=new Uint8Array(a));return a};u=(a,b,c,d=!0)=>{a=w(a)?new URL(a):fa.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};!f.thisProgram&&1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ia||a.context instanceof ia))throw a;});ca=(a,b)=>{process.exitCode=a;throw b;}}else if(da||h)h?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src),n=n.startsWith("blob:")?"":n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1),ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},h&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=f.print||console.log.bind(console),x=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.thisProgram&&(ba=f.thisProgram);f.quit&&(ca=f.quit);var y;f.wasmBinary&&(y=f.wasmBinary);"object"!=typeof WebAssembly&&z("no native wasm support detected");
var B,ka=!1,C,D,la,E,F,ma;function na(){var a=B.buffer;f.HEAP8=C=new Int8Array(a);f.HEAP16=la=new Int16Array(a);f.HEAPU8=D=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAP32=E=new Int32Array(a);f.HEAPU32=F=new Uint32Array(a);f.HEAPF32=new Float32Array(a);f.HEAPF64=new Float64Array(a);f.HEAP64=ma=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var oa=[],pa=[],qa=[];function ra(){var a=f.preRun.shift();oa.unshift(a)}var I=0,sa=null,J=null;
function z(a){f.onAbort?.(a);a="Aborted("+a+")";x(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta=a=>a.startsWith("data:application/octet-stream;base64,"),w=a=>a.startsWith("file://"),K;K="wavpack.wasm";if(!ta(K)){var ua=K;K=f.locateFile?f.locateFile(ua,n):n+ua}function va(a){if(a==K&&y)return new Uint8Array(y);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}
function wa(a){if(!y&&(da||h)){if("function"==typeof fetch&&!w(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>va(a));if(u)return new Promise((b,c)=>{u(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>va(a))}function xa(a,b,c){return wa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{x(`failed to asynchronously prepare wasm: ${d}`);z(d)})}
function ya(a,b){var c=K;y||"function"!=typeof WebAssembly.instantiateStreaming||ta(c)||w(c)||m||"function"!=typeof fetch?xa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){x(`wasm streaming compile failed: ${e}`);x("falling back to ArrayBuffer instantiation");return xa(c,a,b)}))}function ia(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var za=a=>{for(;0<a.length;)a.shift()(f)},Aa=f.noExitRuntime||!0,Ba="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,L=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ba)return Ba.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ca=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},M=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ca(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ea=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.substr(0,b.length-1);return a+b},Fa=a=>{if("/"===a)return"/";a=M(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ga=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(m)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}z("initRandomDevice")},Ha=a=>(Ha=Ga())(a);
function N(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ca(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Ia=[],Ja=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ka=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var p=a.charCodeAt(++g);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>
12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e},La=[];function Ma(a,b){La[a]={input:[],output:[],ea:b};Na(a,Oa)}
var Oa={open(a){var b=La[a.node.rdev];if(!b)throw new O(43);a.tty=b;a.seekable=!1},close(a){a.tty.ea.fsync(a.tty)},fsync(a){a.tty.ea.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ea.sa)throw new O(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.ea.sa(a.tty)}catch(p){throw new O(29);}if(void 0===k&&0===e)throw new O(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ea.ma)throw new O(60);try{for(var e=0;e<d;e++)a.tty.ea.ma(a.tty,b[c+
e])}catch(g){throw new O(29);}d&&(a.node.timestamp=Date.now());return e}},Pa={sa(){a:{if(!Ia.length){var a=null;if(m){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(Ja(a)+
1);a=Ka(a,b,0,b.length);b.length=a;Ia=b}a=Ia.shift()}return a},ma(a,b){null===b||10===b?(ja(L(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(ja(L(a.output,0)),a.output=[])},ya(){return{Ha:25856,Ja:5,Ga:191,Ia:35387,Fa:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},za(){return 0},Aa(){return[24,80]}},Qa={ma(a,b){null===b||10===b?(x(L(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(x(L(a.output,
0)),a.output=[])}};function Ra(a,b){var c=a.Y?a.Y.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Y,a.Y=new Uint8Array(b),0<a.$&&a.Y.set(c.subarray(0,a.$),0))}
var P={aa:null,da(){return P.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.aa||(P.aa={dir:{node:{fa:P.X.fa,ba:P.X.ba,lookup:P.X.lookup,ja:P.X.ja,rename:P.X.rename,unlink:P.X.unlink,rmdir:P.X.rmdir,readdir:P.X.readdir,symlink:P.X.symlink},stream:{ga:P.Z.ga}},file:{node:{fa:P.X.fa,ba:P.X.ba},stream:{ga:P.Z.ga,read:P.Z.read,write:P.Z.write,oa:P.Z.oa,ta:P.Z.ta,va:P.Z.va}},link:{node:{fa:P.X.fa,ba:P.X.ba,readlink:P.X.readlink},stream:{}},pa:{node:{fa:P.X.fa,
ba:P.X.ba},stream:Sa}});c=Ta(a,b,c,d);16384===(c.mode&61440)?(c.X=P.aa.dir.node,c.Z=P.aa.dir.stream,c.Y={}):32768===(c.mode&61440)?(c.X=P.aa.file.node,c.Z=P.aa.file.stream,c.$=0,c.Y=null):40960===(c.mode&61440)?(c.X=P.aa.link.node,c.Z=P.aa.link.stream):8192===(c.mode&61440)&&(c.X=P.aa.pa.node,c.Z=P.aa.pa.stream);c.timestamp=Date.now();a&&(a.Y[b]=c,a.timestamp=c.timestamp);return c},Ka(a){return a.Y?a.Y.subarray?a.Y.subarray(0,a.$):new Uint8Array(a.Y):new Uint8Array(0)},X:{fa(a){var b={};b.dev=8192===
(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.$:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.wa=4096;b.blocks=Math.ceil(b.size/b.wa);return b},ba(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.$!=b))if(0==b)a.Y=null,a.$=0;
else{var c=a.Y;a.Y=new Uint8Array(b);c&&a.Y.set(c.subarray(0,Math.min(b,a.$)));a.$=b}},lookup(){throw Ua[44];},ja(a,b,c,d){return P.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=Va(b,c)}catch(g){}if(d)for(var e in d.Y)throw new O(55);}delete a.parent.Y[a.name];a.parent.timestamp=Date.now();a.name=c;b.Y[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.Y[b];a.timestamp=Date.now()},rmdir(a,b){var c=Va(a,b),d;for(d in c.Y)throw new O(55);delete a.Y[b];a.timestamp=
Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.Y))b.push(c);return b},symlink(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new O(28);return a.link}},Z:{read(a,b,c,d,e){var g=a.node.Y;if(e>=a.node.$)return 0;a=Math.min(a.node.$-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===C.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.Y||a.Y.subarray)){if(g)return a.Y=b.subarray(c,c+d),a.$=d;if(0===a.$&&0===e)return a.Y=b.slice(c,c+d),a.$=d;if(e+d<=a.$)return a.Y.set(b.subarray(c,c+d),e),d}Ra(a,e+d);if(a.Y.subarray&&b.subarray)a.Y.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.Y[e+g]=b[c+g];a.$=Math.max(a.$,e+d);return d},ga(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.$);if(0>b)throw new O(28);return b},oa(a,b,c){Ra(a.node,b+c);a.node.$=Math.max(a.node.$,b+c)},ta(a,b,c,d,e){if(32768!==(a.node.mode&
61440))throw new O(43);a=a.node.Y;if(e&2||a.buffer!==C.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;z();b=void 0;if(!b)throw new O(48);C.set(a,b)}else c=!1,b=a.byteOffset;return{Ma:b,Ea:c}},va(a,b,c,d){P.Z.write(a,b,0,d,c,!1);return 0}}},Wa=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Xa=null,Ya={},Za=[],$a=1,Q=null,ab=!0,O=class{constructor(a){this.name="ErrnoError";this.ha=a}},Ua={};
function R(a,b={}){a=N(a);if(!a)return{path:"",node:null};b=Object.assign({ra:!0,na:0},b);if(8<b.na)throw new O(32);a=a.split("/").filter(k=>!!k);for(var c=Xa,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=Va(c,a[e]);d=M(d+"/"+a[e]);c.ka&&(!g||g&&b.ra)&&(c=c.ka.root);if(!g||b.qa)for(g=0;40960===(c.mode&61440);)if(c=bb(d),d=N(Ea(d),c),c=R(d,{na:b.na+1}).node,40<g++)throw new O(32);}return{path:d,node:c}}
function cb(a){for(var b;;){if(a===a.parent)return a=a.da.ua,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function db(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.length}function Va(a,b){var c=16384===(a.mode&61440)?(c=eb(a,"x"))?c:a.X.lookup?0:2:54;if(c)throw new O(c);for(c=Q[db(a.id,b)];c;c=c.Ca){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.X.lookup(a,b)}
function Ta(a,b,c,d){a=new fb(a,b,c,d);b=db(a.parent.id,a.name);a.Ca=Q[b];return Q[b]=a}function gb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function eb(a,b){if(ab)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function hb(a,b){try{return Va(a,b),20}catch(c){}return eb(a,"wx")}function ib(){for(var a=0;4096>=a;a++)if(!Za[a])return a;throw new O(33);}
function S(a){a=Za[a];if(!a)throw new O(8);return a}function jb(a){var b=-1;U||(U=function(){this.ia={}},U.prototype={},Object.defineProperties(U.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.ia.flags},set(c){this.ia.flags=c}},position:{get(){return this.ia.position},set(c){this.ia.position=c}}}));a=Object.assign(new U,a);-1==b&&(b=ib());a.fd=b;return Za[b]=a}var Sa={open(a){a.Z=Ya[a.node.rdev].Z;a.Z.open?.(a)},ga(){throw new O(70);}};
function Na(a,b){Ya[a]={Z:b}}function kb(a,b){var c="/"===b;if(c&&Xa)throw new O(10);if(!c&&b){var d=R(b,{ra:!1});b=d.path;d=d.node;if(d.ka)throw new O(10);if(16384!==(d.mode&61440))throw new O(54);}b={type:a,La:{},ua:b,Ba:[]};a=a.da(b);a.da=b;b.root=a;c?Xa=a:d&&(d.ka=b,d.da&&d.da.Ba.push(b))}function lb(a,b,c){var d=R(a,{parent:!0}).node;a=Fa(a);if(!a||"."===a||".."===a)throw new O(28);var e=hb(d,a);if(e)throw new O(e);if(!d.X.ja)throw new O(63);return d.X.ja(d,a,b,c)}
function V(a){return lb(a,16895,0)}function mb(a,b,c){"undefined"==typeof c&&(c=b,b=438);lb(a,b|8192,c)}function ob(a,b){if(!N(a))throw new O(44);var c=R(b,{parent:!0}).node;if(!c)throw new O(44);b=Fa(b);var d=hb(c,b);if(d)throw new O(d);if(!c.X.symlink)throw new O(63);c.X.symlink(c,b,a)}function bb(a){a=R(a).node;if(!a)throw new O(44);if(!a.X.readlink)throw new O(28);return N(cb(a.parent),a.X.readlink(a))}
function pb(a,b,c){if(""===a)throw new O(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=M(a);try{e=R(a,{qa:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new O(20);}else e=lb(a,c,0),d=!0;if(!e)throw new O(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new O(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==gb(b)||b&512)?31:eb(e,gb(b)):44))throw new O(c);if(b&512&&!d){c=e;c="string"==typeof c?R(c,{qa:!0}).node:c;if(!c.X.ba)throw new O(63);if(16384===(c.mode&61440))throw new O(31);if(32768!==(c.mode&61440))throw new O(28);if(d=eb(c,"w"))throw new O(d);c.X.ba(c,{size:0,timestamp:Date.now()})}b&=-131713;e=jb({node:e,path:cb(e),flags:b,seekable:!0,position:0,Z:e.Z,Da:[],error:!1});e.Z.open&&e.Z.open(e);!f.logReadFiles||b&1||(qb||={},a in
qb||(qb[a]=1));return e}function rb(a,b,c){if(null===a.fd)throw new O(8);if(!a.seekable||!a.Z.ga)throw new O(70);if(0!=c&&1!=c&&2!=c)throw new O(28);a.position=a.Z.ga(a,b,c);a.Da=[]}var sb;
function W(a,b,c){a=M("/dev/"+a);var d=Wa(!!b,!!c);tb||=64;var e=tb++<<8|0;Na(e,{open(g){g.seekable=!1},close(){c?.buffer?.length&&c(10)},read(g,k,p,r){for(var l=0,q=0;q<r;q++){try{var t=b()}catch(A){throw new O(29);}if(void 0===t&&0===l)throw new O(6);if(null===t||void 0===t)break;l++;k[p+q]=t}l&&(g.node.timestamp=Date.now());return l},write(g,k,p,r){for(var l=0;l<r;l++)try{c(k[p+l])}catch(q){throw new O(29);}r&&(g.node.timestamp=Date.now());return l}});mb(a,d,e)}var tb,X={},U,qb,ub=void 0;
function Y(){var a=E[+ub>>2];ub+=4;return a}
var vb={},xb=()=>{if(!wb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in vb)void 0===vb[b]?delete a[b]:a[b]=vb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);wb=c}return wb},wb,Bb=(a,b,c,d)=>{var e={string:l=>{var q=0;if(null!==l&&void 0!==l&&0!==l){q=Ja(l)+1;var t=yb(q);Ka(l,D,t,q);q=t}return q},array:l=>{var q=yb(l.length);
C.set(l,q);return q}};a=f["_"+a];var g=[],k=0;if(d)for(var p=0;p<d.length;p++){var r=e[c[p]];r?(0===k&&(k=zb()),g[p]=r(d[p])):g[p]=d[p]}c=a.apply(null,g);return c=function(l){0!==k&&Ab(k);return"string"===b?l?L(D,l):"":"boolean"===b?!!l:l}(c)};function fb(a,b,c,d){a||=this;this.parent=a;this.da=a.da;this.ka=null;this.id=$a++;this.name=b;this.mode=c;this.X={};this.Z={};this.rdev=d}
Object.defineProperties(fb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});[44].forEach(a=>{Ua[a]=new O(a);Ua[a].stack="<generic error, no stack>"});Q=Array(4096);kb(P,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");Na(259,{read:()=>0,write:(d,e,g,k)=>k});mb("/dev/null",259);Ma(1280,Pa);Ma(1536,Qa);mb("/dev/tty",1280);mb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ha(a).byteLength);return a[--b]};W("random",c);W("urandom",c);V("/dev/shm");V("/dev/shm/tmp")})();
(function(){V("/proc");var a=V("/proc/self");V("/proc/self/fd");kb({da(){var b=Ta(a,"fd",16895,73);b.X={lookup(c,d){var e=S(+d);c={parent:null,da:{ua:"fake"},X:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Cb={a:(a,b,c,d)=>{z(`Assertion failed: ${a?L(D,a):""}, at: `+[b?b?L(D,b):"":"unknown filename",c,d?d?L(D,d):"":"unknown function"])},j:function(a,b,c){ub=c;try{var d=S(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.ea.ya){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Y();E[e>>2]=25856;E[e+4>>2]=5;E[e+8>>2]=191;E[e+12>>2]=35387;for(var g=0;32>g;g++)C[e+g+17>>0]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?
0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.ea.za)for(e=Y(),a=[],g=0;32>g;g++)a.push(C[e+g+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=Y();return E[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=Y();if(!d.Z.xa)throw new O(59);return d.Z.xa(d,b,e);case 21523:if(!d.tty)return-59;d.tty.ea.Aa&&(g=[24,80],e=Y(),la[e>>1]=g[0],la[e+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(k){if("undefined"==typeof X||"ErrnoError"!==
k.name)throw k;return-k.ha}},o:function(a,b,c,d){ub=d;try{b=b?L(D,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?"/":S(a).path;if(0==e.length)throw new O(44);b=M(g+"/"+e)}var k=d?Y():0;return pb(b,c,k).fd}catch(p){if("undefined"==typeof X||"ErrnoError"!==p.name)throw p;return-p.ha}},b:()=>{z("")},e:a=>{console.error(a?L(D,a):"")},m:()=>Date.now(),c:()=>performance.now(),l:a=>{var b=D.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-B.buffer.byteLength+65535)/65536;try{B.grow(e);na();var g=1;break a}catch(k){}g=void 0}if(g)return!0}return!1},n:(a,b)=>{var c=0;xb().forEach((d,e)=>{var g=b+c;e=F[a+4*e>>2]=g;for(g=0;g<d.length;++g)C[e++>>0]=d.charCodeAt(g);C[e>>0]=0;c+=d.length+1});return 0},f:(a,b)=>{var c=xb();F[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);F[b>>2]=d;return 0},p:a=>{Aa||(f.onExit?.(a),ka=!0);ca(a,new ia(a))},d:function(a){try{var b=
S(a);if(null===b.fd)throw new O(8);b.la&&(b.la=null);try{b.Z.close&&b.Z.close(b)}catch(c){throw c;}finally{Za[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof X||"ErrnoError"!==c.name)throw c;return c.ha}},i:function(a,b,c,d){try{a:{var e=S(a);a=b;for(var g,k=b=0;k<c;k++){var p=F[a>>2],r=F[a+4>>2];a+=8;var l=e,q=g,t=C;if(0>r||0>q)throw new O(28);if(null===l.fd)throw new O(8);if(1===(l.flags&2097155))throw new O(8);if(16384===(l.node.mode&61440))throw new O(31);if(!l.Z.read)throw new O(28);
var A="undefined"!=typeof q;if(!A)q=l.position;else if(!l.seekable)throw new O(70);var ha=l.Z.read(l,t,p,r,q);A||(l.position+=ha);var G=ha;if(0>G){var T=-1;break a}b+=G;if(G<r)break;"undefined"!==typeof g&&(g+=G)}T=b}F[d>>2]=T;return 0}catch(H){if("undefined"==typeof X||"ErrnoError"!==H.name)throw H;return H.ha}},g:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=S(a);rb(e,b,c);ma[d>>3]=BigInt(e.position);e.la&&0===b&&0===c&&(e.la=null);return 0}catch(g){if("undefined"==
typeof X||"ErrnoError"!==g.name)throw g;return g.ha}},h:function(a,b,c,d){try{a:{var e=S(a);a=b;for(var g,k=b=0;k<c;k++){var p=F[a>>2],r=F[a+4>>2];a+=8;var l=e,q=p,t=r,A=g,ha=C;if(0>t||0>A)throw new O(28);if(null===l.fd)throw new O(8);if(0===(l.flags&2097155))throw new O(8);if(16384===(l.node.mode&61440))throw new O(31);if(!l.Z.write)throw new O(28);l.seekable&&l.flags&1024&&rb(l,0,2);var G="undefined"!=typeof A;if(!G)A=l.position;else if(!l.seekable)throw new O(70);var T=l.Z.write(l,ha,q,t,A,void 0);
G||(l.position+=T);var H=T;if(0>H){var nb=-1;break a}b+=H;"undefined"!==typeof g&&(g+=H)}nb=b}F[d>>2]=nb;return 0}catch(Da){if("undefined"==typeof X||"ErrnoError"!==Da.name)throw Da;return Da.ha}},k:(a,b)=>{Ha(D.subarray(a,a+b));return 0}},Z=function(){function a(c){Z=c.exports;B=Z.q;na();pa.unshift(Z.r);I--;f.monitorRunDependencies?.(I);0==I&&(null!==sa&&(clearInterval(sa),sa=null),J&&(c=J,J=null,c()));return Z}var b={a:Cb};I++;f.monitorRunDependencies?.(I);if(f.instantiateWasm)try{return f.instantiateWasm(b,
a)}catch(c){return x(`Module.instantiateWasm callback failed with error: ${c}`),!1}ya(b,function(c){a(c.instance)});return{}}();f._initialiseWavPack=a=>(f._initialiseWavPack=Z.s)(a);f._GetSampleRate=()=>(f._GetSampleRate=Z.t)();f._GetNumChannels=()=>(f._GetNumChannels=Z.u)();f._GetBytesPerSample=()=>(f._GetBytesPerSample=Z.v)();f._GetNumSamples=()=>(f._GetNumSamples=Z.w)();f._DecodeWavPackBlock=(a,b,c)=>(f._DecodeWavPackBlock=Z.x)(a,b,c);f._malloc=a=>(f._malloc=Z.z)(a);f.__ZdaPv=a=>(f.__ZdaPv=Z.A)(a);
f.__ZdaPvm=(a,b)=>(f.__ZdaPvm=Z.B)(a,b);f.__ZdlPv=a=>(f.__ZdlPv=Z.C)(a);f.__ZdlPvm=(a,b)=>(f.__ZdlPvm=Z.D)(a,b);f.__Znaj=a=>(f.__Znaj=Z.E)(a);f.__ZnajSt11align_val_t=(a,b)=>(f.__ZnajSt11align_val_t=Z.F)(a,b);f.__Znwj=a=>(f.__Znwj=Z.G)(a);f.__ZnwjSt11align_val_t=(a,b)=>(f.__ZnwjSt11align_val_t=Z.H)(a,b);f.___libc_calloc=(a,b)=>(f.___libc_calloc=Z.I)(a,b);f.___libc_free=a=>(f.___libc_free=Z.J)(a);f.___libc_malloc=a=>(f.___libc_malloc=Z.K)(a);f.___libc_realloc=(a,b)=>(f.___libc_realloc=Z.L)(a,b);
f._calloc=(a,b)=>(f._calloc=Z.M)(a,b);f._emscripten_builtin_free=a=>(f._emscripten_builtin_free=Z.N)(a);f._emscripten_builtin_malloc=a=>(f._emscripten_builtin_malloc=Z.O)(a);f._free=a=>(f._free=Z.P)(a);f._malloc_size=a=>(f._malloc_size=Z.Q)(a);f._malloc_usable_size=a=>(f._malloc_usable_size=Z.R)(a);f._realloc=(a,b)=>(f._realloc=Z.S)(a,b);f._reallocf=(a,b)=>(f._reallocf=Z.T)(a,b);var zb=()=>(zb=Z.U)(),Ab=a=>(Ab=Z.V)(a),yb=a=>(yb=Z.W)(a);f.ccall=Bb;
f.cwrap=(a,b,c,d)=>{var e=!c||c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&e&&!d?f["_"+a]:function(){return Bb(a,b,c,arguments,d)}};var Db;J=function Eb(){Db||Fb();Db||(J=Eb)};
function Fb(){function a(){if(!Db&&(Db=!0,f.calledRun=!0,!ka)){f.noFSInit||sb||(sb=!0,f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?W("stdin",f.stdin):ob("/dev/tty","/dev/stdin"),f.stdout?W("stdout",null,f.stdout):ob("/dev/tty","/dev/stdout"),f.stderr?W("stderr",null,f.stderr):ob("/dev/tty1","/dev/stderr"),pb("/dev/stdin",0),pb("/dev/stdout",1),pb("/dev/stderr",1));ab=!1;za(pa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=
[f.postRun]);f.postRun.length;){var b=f.postRun.shift();qa.unshift(b)}za(qa)}}if(!(0<I)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ra();za(oa);0<I||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Fb();
